export const PERMISSIONS = {
  VIEW_PERSONAL_PROFILE: 'view_personal_profile',
  VIEW_PERSONAL_PAYMENTS: 'view_personal_payments',
  DOWNLOAD_CERTIFICATE: 'download_certificate',
  VIEW_OPERATIONAL_DASHBOARD: 'view_operational_dashboard',
  MANAGE_ADVOCATES: 'manage_advocates',
  COLLECT_PAYMENTS: 'collect_payments',
  VIEW_REPORTS: 'view_reports',
  MANAGE_SETTINGS: 'manage_settings',
};

export const GROUP_PERMISSIONS: Record<string, string[]> = {
  'Advocate': [
    PERMISSIONS.VIEW_PERSONAL_PROFILE,
    PERMISSIONS.VIEW_PERSONAL_PAYMENTS,
    PERMISSIONS.DOWNLOAD_CERTIFICATE,
  ],
  'Office Staff': [
    PERMISSIONS.VIEW_OPERATIONAL_DASHBOARD,
    PERMISSIONS.MANAGE_ADVOCATES,
    PERMISSIONS.COLLECT_PAYMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_PERSONAL_PROFILE,
  ],
  'Admin Advocate': [
    PERMISSIONS.VIEW_PERSONAL_PROFILE,
    PERMISSIONS.VIEW_PERSONAL_PAYMENTS,
    PERMISSIONS.DOWNLOAD_CERTIFICATE,
    PERMISSIONS.VIEW_OPERATIONAL_DASHBOARD,
    PERMISSIONS.MANAGE_ADVOCATES,
    PERMISSIONS.COLLECT_PAYMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_SETTINGS,
  ],
};
